### ISSUE TITLE
Note becomes read-only after deleting source note

### ISSUE THREAD

**Issue by jotech** [robert7/nixnote2#100]
## Expected vs. actual behavior
Notes sometimes cannot be edited anymore. I realized that it is connected with the read-only flag which was set because of missing resources. The reason seems to be that when images are copied from one note to another the source note always has to be present otherwise the copied image will cause the problem. 
The issue occurred for me while having conflicts during synchronization. I end up with two notes and have to merge manually. Here sometimes I'm copying the content of one note into the other and delete one of the notes. 

## Steps to reproduce the problem
  1. create a note with an image
  2. create another empty note and copy the content from the first note (ctrl+c, ctrl+v)
  3. delete first note
  4. second note is now disabled (read-only mode)

## Specifications
  - Version: NixNote 2.1.3-bbbf0a1, build at Apr  5 2019 at 08:03:26

**Comment by robert7** [comment]
copy paste content from one note where the markup contains the resources (e.g. images) currently doesn't work - the resources are NOT copied.. this then causes them to be missing (and readonly flag due to missing resources).

so currently you have few options

- duplicate the note (this will duplicate the resources) - then update the duplicated note - and all will work
- copy paste note content to new note - then sync - this will discard the resources from the new note - only text will remain- there will be not problem with read only - but resources will vanish
-  copy paste note - then sync - then copy out the resources from original note (e.g. save as to local files), then drag them to new note.

its quite sub-optimal, but now I'm out of time to change it

Pull request welcome...
