### ISSUE TITLE
User settable spaces for <tab>

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#107]
## Feature request

Currently when I pesss \<tab\>, I get 5 spaces.

Python uses 4. The default on many typewriters from way back when was 8.

Would you consider allowing the user to choose how many spaces are inserted upon pressing \<tab\>?

**Comment by robert7** [comment]
I looked it up... So nixnote really inserts 5 non breaking spaces on Tab key... which I find silly function.

The "Tabs"  may have sense in plain text editors and even maybe on rich text editors, where they really works as "Tabs" and it may have sense for source code editors to insert spaces instead of tabs... to get around of problem where each developer has different settings for tabs.... but I don't see much use for tabs in HTML editor (as Evernote/Nixnote is).

In the present version it even worked weirdly as 5 spaces were inserted, then after you started typing, 3 of them were deleted (as the markup as different as the HTML editor wanted it to have..) ..I corrected it in version 2.1.4-f, but I don't see the use case where HTML editor should have configurable amount of fixed spaces to be inserted after pressing Tab.
