### ISSUE TITLE
note fails to sync with EDAMNotFoundException after moving to different shared notebook

### ISSUE THREAD

**Issue by roncanepa** [robert7/nixnote2#108]
## Expected vs. actual behavior
Move note from private notebook to shared notebook and expect that note syncs.  Actual behavior is sync error with `EDAMNotFoundException`

## Steps to reproduce the problem 

  1. have a note saved and synced to a normal private notebook like "My Notebook"
  1. move the note to a shared notebook (where a different account is the "owner" of the shared notebook) via the dropdown menu in the upper-right of nixnote2
  1. attempt to sync.  Receive "sync error" popup with `EDAMNotFoundException` in the log.

Note id 994131bf-2b2f-4c01-87ec-9d991e0fa6bf in the log is the one I moved.

[messages.zip](https://github.com/robert7/nixnote2/files/3252819/messages.zip)

## Specifications

Version: 201905262116~2.1.3~ubuntu18.04.1 via https://launchpad.net/~nixnote PPA

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

I can provide the note text from logs if necessary.

**Comment by robert7** [comment]
Hi,
try the latest version 2.1.4-c. This has updated the QEvercloud (evernote client) from version v2 to v4. The version is now available both in develop and master branch. This could make a difference. Also the logging is a bit improved - pls post a log from the newest nixnote version.

`EDAMNotFoundException` means `caller asks to perform an operation on an object that does not exist`..

I suppose the problem is nixnote calls `updateNote` instead of `createNote` as the note doesn't not exist in the new notebook. 
I'll have a more detailed look later.

**Comment by robert7** [comment]
Update: the bug is still present in v2.1.4-c..
There is a quick **workaround**: move the note to shared notebook, then duplicate it (right click/Duplicate note), then delete the moved note. Then sync. The duplicate note will sync.
It will have " - copy" in the title, but you can update it..

**Comment by HaleTom** [comment]
I just bumped into this after trying to move a bunch of notes (#160 relates).

Cheers for the work-around.  To make life easier (I had about 30 notes broken on move), sort all notes:

View -> Sort Notes By -> Unsynced first.

NB: All duplicated notes will have their timestamps set to the time of duplication.
