### ISSUE TITLE
Open multiple notes in different windows or split window

### ISSUE THREAD

**Issue by dhorka** [robert7/nixnote2#116]
I would like to be able to open two different notes in an external window as it is done in the official evernote client or be able to split the window to see multiple notes at the same time.

**Comment by robert7** [comment]
yes you can open multiple notes at the same time either in new window or in a new tab

![screen_20190703_05](https://user-images.githubusercontent.com/1135218/60577134-1299fd80-9d7f-11e9-82a0-a031fb74650c.png)

![screen_20190703_04](https://user-images.githubusercontent.com/1135218/60577148-19c10b80-9d7f-11e9-84c1-cece82b85508.png)

**Comment by dhorka** [comment]
Tabs are not working in my setup :( I do not know why, I am using Version: 201906041316~2.1.4-c~ubuntu16.04.1

Moreover, it is true you can open different notes in the explorer, but, it is not possible open a note in a different window from an internal link(for this reason I didn't realize that exists this option). Imagine you have a table of contents with links to several notes, and you want to open them in different windows. In the version that I have installed this option is not available.

**Comment by robert7** [comment]
Tabs should work. Just right click note in list of notes, then select "Open Note in New Tab" ... see my screenshoot.

Open note in "new Window on right click" could be added, but due to lack of time currently its out of my scope. But pull requests are welcome as always.

Maybe you can adjust your workflow to be able to easily find notes by search (e.q. common keyword by list of contents) , then you can open them in new window.
