### ISSUE TITLE
Donation button for NixNote Homepage?

### ISSUE THREAD

**Issue by lubobde** [robert7/nixnote2#122]
Hi Robert,

I am a big fan of NixNote, thank's  lot for taking care of this project!

There is no donation button on the nixnote homepage. Can I support you by sending a little donation via paypal directly to your email address?

Lucius

**Comment by robert7** [comment]
Hi @lubobde 
I did not mention donation on the project page, because I don't expect to get money from the project. 
I didn't plan to "take over" either... it just happened someway as the original maintainer is not available/disappeared.

But yes, any donation is appreciated and you can send any amount you want to my email address nightingale7@gmail.com.
Thanks in advance!

**Comment by robert7** [comment]
I added donation info to About box & main readme
Donations possible via: https://paypal.me/nixnote2
