### ISSUE TITLE
UNRECOGNIZED_ERROR_CODE after workaround for #108

### ISSUE THREAD

**Issue by HaleTom** [robert7/nixnote2#163]
## Expected vs. actual behavior

I expected sync to complete after following [this workaround](https://github.com/robert7/nixnote2/issues/108#issuecomment-498961099) for #108.

Sadly it didn't.

I was getting an `UNRECOGNIZED_ERROR_CODE` message, so restarted Nixnote with `--logLevel=1`

Just as I was going to reproduce the error and capture logs as per the Wiki, the sync succeeded.

The attached is from my `tmux` scrollback buffer:

[EDAM.txt](https://github.com/robert7/nixnote2/files/5287873/EDAM.txt)

Related issues: #137 #142 #155 

Feel free to close as dupe if you don't feel there's anything new here.

## Steps to reproduce the problem (or [log file](https://github.com/robert7/nixnote2/wiki/HowTo---Add-log-file-to-the-github-issue))

Sadly, I can't reproduce the issue anymore.

I had a hunch about one of my notes based on some weird UI behaviour.  It was titled `fzf setup`, and appears to be mentioned in the logging.  What I did was duplicate it and then remove the original.

## Specifications

  - Version: 2.1.6-aa5cfeb8

**Comment by robert7** [comment]
Did you try the older Version (AppImage e.g. 2.1.4 or 2.1.3)? This should display the correct error code.
In the current version the error code recognition is broken unfortunately. 

The fix would require upgrade to QEvercloud 6, which I actually started in feature branch feature/rs-2020-04-qevercloud6; but currently I have no time to finish it; unfortunetely due to API changes its far from trivial.
