### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by krkhan** [robert7/nixnote2#170]
Thank you for an *amazing* open-source project. It has become essential to my daily productivity. Also, I apologize if this is not the right forum for bringing this up but I couldn't think of a better option.

Can we please add a clarifying statement to the `README` about the project status? The last commit to the `master` branch was some 8 months ago. This being open-source it's absolutely okay if the status is `under active development`, `maintenance only`, `will only update if Evernote API breaks` or anything along the lines. Even `use at your own risk, not maintained` would go a long way in providing some clarity.

Once again, thank you for helming the Evernote efforts on *nix for the last few years.

Cheers!

**Comment by robert7** [comment]
Sorry I don't have any time currently for the project and I don't use it any more (as I'm migrated do macOS).
Anyone who is interested, can fork & continue, but currently none does, as far I know..

So far I know Nixnote work quite fine for many people... in case there would be some breaks in Evernote API, I'm willing to investigate and fix if I can.  Otherwise I do some "must have"maintenance.
I'll update the project README later..

**Comment by krkhan** [comment]
Thank you for clarifying!

**Comment by robert7** [comment]
I leave the issue open.. for anyone having the same question
