### ISSUE TITLE
Release page: invalid formatting (in one line)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [robert7/nixnote2#199]
![image](https://user-images.githubusercontent.com/3514015/232216915-e6fad9be-6555-4ecb-884c-5c1d71fe2952.png)

**Comment by robert7** [comment]
please explain more, don't understand what do you mean?

what is invalid?

**Comment by vitaly-zdanevich** [comment]
Looks like the description is in one line.

**Comment by robert7** [comment]
> Looks like the description is in one line.
This is actually intention. Why it is a problem?

**Comment by vitaly-zdanevich** [comment]
We have `-` multiple times - like starting of a new line.

**Comment by robert7** [comment]
OK, now I understand what you mean.
On one side, I wanted to put a few different things inside - so kind of "bullet points", but there are also some sentences. And I wanted to have if "compact".

I agree, the formatting isn't the nicest. But in order to change the formatting, I would manually edit all the previous release texts. Which I don't like.
