### ISSUE TITLE
deleted (empty) tags keep reappearing every time I launch nixnote, AND **unknown** tag on loads of notes

### ISSUE THREAD

**Issue by memo** [robert7/nixnote2#48]
Thank you for this version 2.1! I had been struggling with 2.0.2 for months (maybe even years), with the dreaded tag 1004 sync errors. I just upgraded to 2.1 and no longer get that error, but I have other issues relating to tags.

I have thousands of notes with tens of tags, which unfortunately have not been synced in a while, due to the 1004 error. I used to have quite a complex tag hierarchy, but have now flattened it as much as possible (most tags in the root, with occasional single level deep tags as well).

## Expected vs. actual behavior
I have deleted a bunch of tags, but every time I relaunch nixnote2, they all reappear (with 0 notes).
I also have loads of notes appearing to be tagged with **unknown**.
Loads of notes also display a black triangle before their name. I don't know if this is related (not necessarily only notes with unknown tags).

## Specifications
Version: 2.1.0-beta4j~201810131046~ubuntu16.04.1

**Comment by robert7** [comment]
Hi
the handling of the "tags" isn't perfect in Nixnote. I know this... and to completely fix it, is currently "out of scope" for me. I think it is due to partly redundant data structures in the database, which sometimes get a bit out of sync.
See https://github.com/robert7/nixnote2/issues/10
And wiki article https://github.com/robert7/nixnote2/wiki/HowTo---Do-changes-in-tag-structure

What I recommend to you:
* first fix you tag structure - do this either in Evernote web client or official Windows client (e.g. via virtualbox
  * I do like this - like ~one time in year )
  * you may done this already
* after you are sure in cloud its all OK, then do a fresh full sync (backup $HOME/.nixnote then delete and start from scratch). Be aware that if you have many notes - then initial sync will take really long time - but just let it run over night or like this and it will eventually finish - see https://github.com/robert7/nixnote2/wiki/Getting-started
* done :) 

Further comments... I used a "tags" a lot before... but then I noticed its most times simply not worth the effort. For my case I invested a lot of time for tagging, but if I needed the tags in search, mostly it did not really worked for search (I mean not technically, but even if the tag were in place, it did not really helped me to find the content). 

So now I try to put meaningful words in the title (sometimes I append them after the title). And most times I find them and the "[sort by relevance](https://github.com/robert7/nixnote2/wiki/Results-sorted-by-relevance-to-search-query)" feature puts them in the first hits. Now nowadays I almost don't use tagging.

**Comment by robert7** [comment]
Btw the "1004 error" was just log display issue and did not really cause your problem - the problem with "tags out of sync" is much deeper. But even if "not perfect" the tags basically works in nixnote - for like >95% cases... which is "good enough" for my use cases :)

**Comment by memo** [comment]
hi thanks for the info. Right now I'm not convinced that everything is perfectly synced up, and it's difficult to check with 1000s of notes (e.g. I can see that the number of notes per tag in nixnote is definitely different to the number of notes for the same tags in the web client). So I'm a bit stuck with trying to fix it locally on linux unfortunately! I'll have a play around and see what happens :/

**Comment by robert7** [comment]
You can check, whenever all is synced by sorting by "Sync" column. If no note is marked "dirty", then you can be quite sure, all notes were synced to cloud. It could be that some tags are not exactly the same on "local" & "cloud", but content of notes should be. So you could lose some tags, but should not lose any content. Although Its difficult to be 100% sure.

**Comment by robert7** [comment]
Further you could mark all local notes as "dirty" - e.g. by creating a new tag and assigning it to all notes. 

This would re-upload everything to cloud. But this could take really long time, as Evernote limits how much you can upload per hour and in case you have free account, there is also limit per month.
