### ISSUE TITLE
Provide some sort of update mechanism

### ISSUE THREAD

**Issue by github-t** [robert7/nixnote2#6]
Thanks for keeping Nixnote going (an thank for referring me!)!

Not sure if its possible with appimages but a PPA for Ubuntu or some sort of automatic updating mechanism is desirable.  I know snaps can update themselves - not sure of what's possible with appimages.  Is there already an easy way that I'm missing?  Or is there an easy way to set something like this up?

**Comment by robert7** [comment]
[AppImage's have update possibility](https://github.com/AppImage/AppImageUpdate), but I did not implemented (yet.. and not sure if i'll come to that).

PPA would be nice, but the debian packaging is still a bit mystery to me, so I'm currently waiting, [whenewer Art will be so kind to help with PPA](https://github.com/artmg/nixnote2-packaging/issues/31) (he did for upstream repository).

**Comment by robert7** [comment]
It beginning I did not even plan to provide binaries... I just [wanted to make few improvements and post few PRs to upstream](https://nixnotes-21.blogspot.com/2018/08/hello-world.html)... So I'm already quite ahead of the plan anyway :)

**Comment by robert7** [comment]
So here is the new PPA for Ubuntu: https://launchpad.net/~robert7/+archive/ubuntu/nixnote21
you add the PPA as usual then
`sudo apt install nixnote21`
then it will update with the ubuntu usual mechanism

**Comment by github-t** [comment]
Wow thanks!

Does installing from this PPA imply that it'll gracefully upgrade an existing 2.0.2 install from nixnote2-daily PPA?  And I'm assuming its also safe to remove the nixnote2-daily PPA - yes?

**Comment by robert7** [comment]
The [new PPA](https://launchpad.net/~robert7/+archive/ubuntu/nixnote21) is independent from both official "nixnote2" package and the "[daily  nixnote2 PPA](https://launchpad.net/~nixnote/+archive/ubuntu/nixnote2-daily)". This is because the original maintainer @baumgarr isn't available.

That means the **v2.0 will not automatically upgrade to v2.1** - you need to take action to subscribe to the new one.

I felt some people were not yet fully confident with making "clear cut" upgrade, so I renamed both the application and the package to "nixnote21". That means you can have both installed:
1, either official 2.0.2 or 2.0 daily build (which are basically the same) and the package is named "nixnote2"
2, new "nixnote21"
They will happily coexist and don't conflict even with the same data - just don't run both at the same time (there should be protection on both sides, but better not try). More detail in [v2 to v2.1 migration info](https://github.com/robert7/nixnote2/wiki/Migration-v2.0-to-v2.1).

To install "nixnote21" enter `sudo add-apt-repository ppa:robert7/nixnote21 -y -u && sudo apt install nixnote21 -y`.
Then at any time later you can uninstall original "nixnote2" and then remove the old PPA.

**Comment by github-t** [comment]
That's good information, thanks.  Everything worked like a charm!

Should this PPA be considered to be a daily / weekly / whenever style of releases?  Or whenever there's a version number bump?  Or something else all together?

**Comment by robert7** [comment]
>Should this PPA be considered to be a daily / weekly / whenever style of releases? Or whenever there's a version number bump?

The idea is, that the "nixnote21" PPA should be the "stable build". In the future it should build automatically, whenever there is push into master branch - and this should happen, when there is version number change.
I will probably later create one more PPA for the development version.

**Comment by artmg** [comment]
exactly, robert, you can create a daily PPA which automatically builds on every commit, so that people who want the very latest features take their own risk. Then you decide based on your testing when to release that as a stable build in the main PPA

**Comment by robert7** [comment]
@artmg : yes 
@github-t : there will be slight change - the new PPA will be moved in the Launchpad under the "nixnote" Team https://launchpad.net/~nixnote; I will describe the change after the transition is done. But basically everything stays the same, just the PPA url will change.

**Comment by github-t** [comment]
Can confirm that everything works as you've published in the wiki.

Also liking the updates.  Thanks again for all your work!
