### ISSUE TITLE
Business cards images not visible in nixnote2

### ISSUE THREAD

**Issue by mickmattes** [robert7/nixnote2#91]
Hi,

I have encountered a problem with scanned business cards. When I use Evernote Mobile (Android) to scan business cards, and refresh the view in nixnote, I only see a little blue square with a white questionmark inside it. (See screnn shot). This happens only with business cards and **not** with normal images that were scanned from my phone.

What could be the problem here?

Thanks in advance!
![bcards](https://user-images.githubusercontent.com/43680093/53733512-7f5cc400-3e81-11e9-801a-54ae6a04d458.png)

**Comment by robert7** [comment]
Hi,
I did a quick check, as I never used the "scan business card" feature before.. it really doesn't work.
Although technically is synced down correctly.
Also the note does get corrupted, if you try modify it in nixnote (so don't try :) ).
It will check, if it can be easily fixed.

In my case the business card got scanned in 18MB PNG file ...OMG Evernote..

**Comment by mickmattes** [comment]
Thank you Robert, I'm looking forward to it

**Comment by robert7** [comment]
it seems to be a bug of Evernote, because its adds the card image as "png" (mime type in media data is "png" and also the image is a "png")
but in the ENML (evernotes markup) the type is set to "jpg"

snippet from ENML:
`<div style="x-evernote:card-image;width: 500px; height:auto; padding: 20px; margin-bottom: 20px;"><en-media style="width: 93%%;height:auto;margin-left: 3.5%%;" hash="666ecc20e75710d7c32879fa8a0bdd79" type="image/jpeg" /></div>`

then nixnote saves the data locally as "png" (as advertised in the media data)
but in the markup it looks for "jpg"
i will try to look if I can ignore the "type" set in the "en-media" tag .. not sure it will be easily possible

**Comment by robert7** [comment]
The problem should be fixed in version 2.1.3-h which will be available shortly.
Please retest.

It also possible to edit "business cards" in nixnote (although it will change the style of the card a little bit - the styling of the photo image will be removed; but this should be OK. If you don't like the style change, then don't edit the cards in nixnote).

**Comment by mickmattes** [comment]
Yep, it's fixed. Nice work! Thank you :+1:

**Comment by robert7** [comment]
thx for info!
